
[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#1d1f21"
foreground = "#c5c8c6"

[cursor]
blink_interval = 300
blink_timeout = 0

[cursor.style]
blinking = "Always"

[font]
size = 10.5

[font.normal]
# family = "JuliaMono Nerd Font Mono"
# style = "Medium"
# family = "M+CodeLat50 Nerd Font"
family = "M+CodeLat60 Nerd Font"
style = "Medium"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Super" # Make sure disable Gnome's "Focus the active notification" key -- Win + N

[[mouse.bindings]]
action = "ExpandSelection"
mouse = "Middle"

[[mouse.bindings]]
action = "ExpandSelection"
mods = "Control"
mouse = "Middle"

[[mouse.bindings]]
action = "PasteSelection"
mode = "~Vi"
mouse = "Right"

[selection]
save_to_clipboard = true

[window]
startup_mode = "Maximized"
padding = { x = 4, y = 0 }

[general]
import = ["~/.dotfiles/alacritty-dracula-theme/dracula.toml"]
